CREATE DATABASE MY_DB;

USE MY_DB;
IF NOT EXISTS(SELECT * FROM sys.tables WHERE [name] ='STUDENT')
--Egane oru table ella ennindel ee table create aakanam
--so we are giving it in begin and end
BEGIN
	CREATE TABLE STUDENT(
		ID INT PRIMARY KEY IDENTITY,
		FIRST_NAME NVARCHAR(50) NOT NULL,
		LASTNAME NVARCHAR(50) NOT NULL,
		EMAIL NVARCHAR(100) NOT NULL UNIQUE
	);
END

INSERT INTO STUDENT(FIRST_NAME,LASTNAME,EMAIL)
VALUES 
	('John' , 'Doe', 'john.doe@example.com'),
	('Jane', 'Smith', 'jane.smith@example.com'),
	('Michael', 'Johnson', 'michael.johnson@example.com')
	;



--or like this we can give  object id null aanegil namuk table create cheynam endegil namuk obj id return cheyum so create aakanda

IF OBJECT_ID('dbo.subject') IS NULL
BEGIN 
	CREATE TABLE subject(
	id INT PRIMARY KEY IDENTITY,
	name NVARCHAR(100) NOT NULL UNIQUE
	)
END


INSERT INTO subject (name)
VALUES
	('chemistry'),
	('math'),
	('computer science');



IF OBJECT_ID('dbo.MARK') IS NULL
BEGIN 
	CREATE TABLE MARK(
	ID INT PRIMARY KEY IDENTITY,
	STUDENT_ID INT NOT NULL,
	SUBJECT_ID INT NOT NULL,
	MARK INT NOT NULL,
	CONSTRAINT FK_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
    CONSTRAINT FK_Subject FOREIGN KEY (Subject_ID) REFERENCES subject(ID),

	)
END


INSERT INTO MARK (STUDENT_ID ,SUBJECT_ID,MARK)
VALUES
	('1','1','80'),
	('1','2','90'),
	('1','3','86'),
	('2','1','50'),
	('2','2','60'),
	('2','3','76'),
	('3','1','80'),
	('3','2','95'),
	('3','3','36');
------------------

SELECT * FROM STUDENT;
SELECT * FROM subject;
SELECT * FROM MARK;


SELECT * FROM MARK WHERE STUDENT_ID=(SELECT ID FROM STUDENT WHERE EMAIL='john.doe@example.com');

--inner join

SELECT STUDENT.ID AS STUDENT_ID,STUDENT.FIRST_NAME,STUDENT.LASTNAME,MARK.MARK,MARK.SUBJECT_ID
FROM STUDENT INNER JOIN MARK
ON STUDENT_ID=MARK.STUDENT_ID;



SELECT
	STUDENT.ID AS STUDENT_ID,
	MARK.ID AS MARK_ID,
	STUDENT.FIRST_NAME,
	STUDENT.LASTNAME,
	MARK.MARK,
	MARK.SUBJECT_ID
FROM STUDENT INNER JOIN MARK
ON STUDENT_ID=MARK.STUDENT_ID;


--LEFT JOIN

SELECT
	STUDENT.ID AS STUDENT_ID,
	MARK.ID AS MARK_ID,
	STUDENT.FIRST_NAME,
	STUDENT.LASTNAME,
	MARK.MARK,
	MARK.SUBJECT_ID
FROM STUDENT LEFT JOIN MARK
ON STUDENT_ID=MARK.STUDENT_ID;

--3 TABLES included

SELECT
	STUDENT.ID AS STUDENT_ID,
	MARK.ID AS MARK_ID,
	STUDENT.FIRST_NAME,
	STUDENT.LASTNAME,
	MARK.MARK,
	MARK.SUBJECT_ID,
	subject.name
FROM STUDENT INNER JOIN MARK ON STUDENT_ID=MARK.STUDENT_ID
INNER JOIN subject ON MARK.subject_ID = subject_ID;